In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/testdataset/racee5.csv
/kaggle/input/teststrategy/TestDataset.csv
/kaggle/input/strategydataset/Race_Strategy_COMPLETE_DATASET.csv
/kaggle/input/traindataset/ModifiedRaceStrategy.csv

**Reading The CSV**

In [2]:
data = pd.read_csv("../input/testdataset/racee5.csv")
data

,Unnamed: 0,Time,DriverNumber,LapTime,LapNumber,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,...,Compound,TyreLife,FreshTyre,Stint,LapStartTime,Team,Driver,TrackStatus,IsAccurate,LapStartDate
0,0,0 days 01:03:53.401000,1,NaN,1,0 days 00:23:51.168000,NaN,NaN,0 days 00:00:35.848000,0 days 00:00:26.431000,...,MEDIUM,1.0,True,1,0 days 01:02:16.435000,Red Bull Racing,VER,1,False,2022-05-08 19:33:16.443
1,1,0 days 01:05:27.943000,1,0 days 00:01:34.542000,2,NaN,NaN,0 days 00:00:32.267000,0 days 00:00:35.970000,0 days 00:00:26.305000,...,MEDIUM,2.0,True,1,0 days 01:03:53.401000,Red Bull Racing,VER,1,True,2022-05-08 19:34:53.409
2,2,0 days 01:07:02.493000,1,0 days 00:01:34.550000,3,NaN,NaN,0 days 00:00:32.182000,0 days 00:00:36.062000,0 days 00:00:26.306000,...,MEDIUM,3.0,True,1,0 days 01:05:27.943000,Red Bull Racing,VER,1,True,2022-05-08 19:36:27.951
3,3,0 days 01:08:36.780000,1,0 days 00:01:34.287000,4,NaN,NaN,0 days 00:00:32.092000,0 days 00:00:35.968000,0 days 00:00:26.227000,...,MEDIUM,4.0,True,1,0 days 01:07:02.493000,Red Bull Racing,VER,1,True,2022-05-08 19:38:02.501
4,4,0 days 01:10:11.100000,1,0 days 00:01:34.320000,5,NaN,NaN,0 days 00:00:32.028000,0 days 00:00:35.942000,0 days 00:00:26.350000,...,MEDIUM,5.0,True,1,0 days 01:08:36.780000,Red Bull Racing,VER,1,True,2022-05-08 19:39:36.788
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,1051,0 days 01:05:38.876000,24,0 days 00:01:37.487000,2,NaN,NaN,0 days 00:00:33.346000,0 days 00:00:37.351000,0 days 00:00:26.790000,...,MEDIUM,2.0,True,1,0 days 01:04:01.389000,Alfa Romeo,ZHO,1,True,2022-05-08 19:35:01.397
1052,1052,0 days 01:07:15.603000,24,0 days 00:01:36.727000,3,NaN,NaN,0 days 00:00:33.214000,0 days 00:00:36.851000,0 days 00:00:26.662000,...,MEDIUM,3.0,True,1,0 days 01:05:38.876000,Alfa Romeo,ZHO,1,True,2022-05-08 19:36:38.884
1053,1053,0 days 01:08:51.334000,24,0 days 00:01:35.731000,4,NaN,NaN,0 days 00:00:32.737000,0 days 00:00:36.503000,0 days 00:00:26.491000,...,MEDIUM,4.0,True,1,0 days 01:07:15.603000,Alfa Romeo,ZHO,1,True,2022-05-08 19:38:15.611
1054,1054,0 days 01:10:27.217000,24,0 days 00:01:35.883000,5,NaN,NaN,0 days 00:00:32.771000,0 days 00:00:36.636000,0 days 00:00:26.476000,...,MEDIUM,5.0,True,1,0 days 01:08:51.334000,Alfa Romeo,ZHO,1,True,2022-05-08 19:39:51.342
1055,1055,0 days 01:12:28.922000,24,0 days 00:02:01.705000,6,NaN,0 days 01:12:26.853000,0 days 00:00:34.043000,0 days 00:00:38.314000,0 days 00:00:49.348000,...,MEDIUM,6.0,True,1,0 days 01:10:27.217000,Alfa Romeo,ZHO,1,False,2022-05-08 19:41:27.225

**Keeping only the longest tyre life value**

In [3]:
smax = -1
smax_ind = -1
maxi = -1
maxi_ind = -1
for index, row in data.iterrows():
    if(row['TyreLife'] > maxi):
        if(smax >= 0):
            data = data.drop(smax_ind)
        smax = maxi
        smax_ind = maxi_ind
        maxi = row['TyreLife']
        maxi_ind = index
    else:
        smax = -1
        smax = -1
        maxi = row['TyreLife']
        maxi_ind = index
data

,Unnamed: 0,Time,DriverNumber,LapTime,LapNumber,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,...,Compound,TyreLife,FreshTyre,Stint,LapStartTime,Team,Driver,TrackStatus,IsAccurate,LapStartDate
24,24,0 days 01:41:28.791000,1,0 days 00:01:33.286000,25,NaN,NaN,0 days 00:00:31.535000,0 days 00:00:35.703000,0 days 00:00:26.048000,...,MEDIUM,25.0,True,1,0 days 01:39:55.505000,Red Bull Racing,VER,1,True,2022-05-08 20:10:55.513
25,25,0 days 01:43:07.296000,1,0 days 00:01:38.505000,26,NaN,0 days 01:43:05.289000,0 days 00:00:31.470000,0 days 00:00:35.701000,0 days 00:00:31.334000,...,MEDIUM,26.0,True,1,0 days 01:41:28.791000,Red Bull Racing,VER,1,False,2022-05-08 20:12:28.799
55,55,0 days 02:35:08.695000,1,0 days 00:01:31.740000,56,NaN,NaN,0 days 00:00:30.504000,0 days 00:00:35.334000,0 days 00:00:25.902000,...,HARD,30.0,True,2,0 days 02:33:36.955000,Red Bull Racing,VER,2,True,2022-05-08 21:04:36.963
56,56,0 days 02:36:40.153000,1,0 days 00:01:31.458000,57,NaN,NaN,0 days 00:00:30.446000,0 days 00:00:35.156000,0 days 00:00:25.856000,...,HARD,31.0,True,2,0 days 02:35:08.695000,Red Bull Racing,VER,1,True,2022-05-08 21:06:08.703
79,79,0 days 01:38:26.570000,16,0 days 00:01:33.141000,23,NaN,NaN,0 days 00:00:31.268000,0 days 00:00:35.943000,0 days 00:00:25.930000,...,MEDIUM,23.0,True,1,0 days 01:36:53.429000,Ferrari,LEC,1,True,2022-05-08 20:07:53.437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1028,1028,0 days 01:31:15.518000,4,0 days 00:01:39.685000,18,NaN,0 days 01:31:13.595000,0 days 00:00:32.049000,0 days 00:00:36.282000,0 days 00:00:31.354000,...,MEDIUM,18.0,True,1,0 days 01:29:35.833000,McLaren,NOR,1,False,2022-05-08 20:00:35.841
1048,1048,0 days 02:03:11.143000,4,0 days 00:01:33.909000,38,NaN,NaN,0 days 00:00:31.912000,0 days 00:00:36.178000,0 days 00:00:25.819000,...,HARD,20.0,True,2,0 days 02:01:37.234000,McLaren,NOR,1,True,2022-05-08 20:32:37.242
1049,1049,0 days 02:04:45.333000,4,0 days 00:01:34.190000,39,NaN,NaN,0 days 00:00:31.813000,0 days 00:00:36.293000,0 days 00:00:26.084000,...,HARD,21.0,True,2,0 days 02:03:11.143000,McLaren,NOR,1,True,2022-05-08 20:34:11.151
1054,1054,0 days 01:10:27.217000,24,0 days 00:01:35.883000,5,NaN,NaN,0 days 00:00:32.771000,0 days 00:00:36.636000,0 days 00:00:26.476000,...,MEDIUM,5.0,True,1,0 days 01:08:51.334000,Alfa Romeo,ZHO,1,True,2022-05-08 19:39:51.342
1055,1055,0 days 01:12:28.922000,24,0 days 00:02:01.705000,6,NaN,0 days 01:12:26.853000,0 days 00:00:34.043000,0 days 00:00:38.314000,0 days 00:00:49.348000,...,MEDIUM,6.0,True,1,0 days 01:10:27.217000,Alfa Romeo,ZHO,1,False,2022-05-08 19:41:27.225

**Converting to CSV**

In [4]:
#data.to_csv("TestDataset.csv")

**Reading The Updated CSV**

In [5]:
Train = pd.read_csv("../input/traindataset/ModifiedRaceStrategy.csv")
Train

,Sno,RaceNo,Time,DriverNumber,LapTime,LapNumber,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,Compound,TyreLife,FreshTyre,Stint,LapStartTime,Team,Driver,TrackStatus,IsAccurate,LapStartDate
0,1,1,0 days 01:25:39.164000,16,0 days 00:01:39.629000,14,NaN,NaN,0 days 00:00:31.939000,0 days 00:00:43.019000,...,SOFT,14,True,1,0 days 01:23:59.535000,Ferrari,LEC,1,True,24:59.6
1,2,1,0 days 01:27:21.205000,16,0 days 00:01:42.041000,15,NaN,0 days 01:27:19.419000,0 days 00:00:31.789000,0 days 00:00:43.159000,...,SOFT,15,True,1,0 days 01:25:39.164000,Ferrari,LEC,2,False,26:39.2
2,3,1,0 days 01:52:12.744000,16,0 days 00:01:39.354000,30,NaN,NaN,0 days 00:00:31.675000,0 days 00:00:43.019000,...,SOFT,18,False,2,0 days 01:50:33.390000,Ferrari,LEC,1,True,51:33.4
3,4,1,0 days 01:53:54.289000,16,0 days 00:01:41.545000,31,NaN,0 days 01:53:52.515000,0 days 00:00:31.577000,0 days 00:00:42.878000,...,SOFT,19,False,2,0 days 01:52:12.744000,Ferrari,LEC,1,False,53:12.8
4,5,1,0 days 02:16:50.133000,16,0 days 00:01:37.413000,45,NaN,NaN,0 days 00:00:31.297000,0 days 00:00:42.090000,...,MEDIUM,14,True,3,0 days 02:15:12.720000,Ferrari,LEC,1,True,16:12.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,389,4,0 days 02:33:47.699000,3,0 days 00:01:21.577000,61,NaN,NaN,0 days 00:00:25.993000,0 days 00:00:28.199000,...,HARD,31,True,4,0 days 02:32:26.122000,McLaren,RIC,1,True,33:26.1
389,390,4,0 days 02:35:14.136000,3,0 days 00:01:26.437000,62,NaN,NaN,0 days 00:00:27.728000,0 days 00:00:28.710000,...,HARD,32,True,4,0 days 02:33:47.699000,McLaren,RIC,1,True,34:47.7
390,391,4,0 days 01:12:48.177000,14,0 days 00:01:39.685000,5,NaN,NaN,0 days 00:00:32.192000,0 days 00:00:34.053000,...,INTERMEDIATE,5,True,1,0 days 01:11:08.492000,Alpine,ALO,1,False,12:08.5
391,392,4,0 days 01:14:28.422000,14,0 days 00:01:40.245000,6,NaN,0 days 01:14:23.967000,0 days 00:00:30.919000,0 days 00:00:32.115000,...,INTERMEDIATE,6,True,1,0 days 01:12:48.177000,Alpine,ALO,1,False,13:48.2
392,393,4,0 days 01:03:54.806000,55,NaN,0,NaN,NaN,NaN,NaN,...,INTERMEDIATE,1,True,1,0 days 01:02:03.225000,Ferrari,SAI,24,False,03:03.2

**Getting the Explanatory Variables**

In [6]:
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
le = LabelEncoder()
X_Train = Train[['DriverNumber','LapNumber','Compound', 'FreshTyre', 'Stint', 'Team', 'Driver']]
X_Train['Compound'] = le.fit_transform(X_Train['Compound'])
X_Train['FreshTyre'] = le.fit_transform(X_Train['FreshTyre'])
X_Train['Driver'] = le.fit_transform(X_Train['Driver'])
X_Train['Team'] = le.fit_transform(X_Train['Team'])
X_Train

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

     DriverNumber  LapNumber  Compound  FreshTyre  Stint  Team  Driver
0              16         14         3          1      1     4       7
1              16         15         3          1      1     4       7
2              16         30         3          0      2     4       7
3              16         31         3          0      2     4       7
4              16         45         2          1      3     4       7
..            ...        ...       ...        ...    ...   ...     ...
388             3         61         0          1      4     6      13
389             3         62         0          1      4     6      13
390            14          5         1          1      1     2       1
391            14          6         1          1      1     2       1
392            55          0         1          1      1     4      15

[393 rows x 7 columns]

In [7]:
Y_Train = Train[['TyreLife']]
Y_Train

     TyreLife
0          14
1          15
2          18
3          19
4          14
..        ...
388        31
389        32
390         5
391         6
392         1

[393 rows x 1 columns]

**Test Data**

In [8]:
Test = pd.read_csv("../input/teststrategy/TestDataset.csv")

from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
le = LabelEncoder()
X_Test = Test[['DriverNumber','LapNumber', 'Compound', 'FreshTyre', 'Stint', 'Team', 'Driver']]
X_Test['Compound'] = le.fit_transform(X_Test['Compound'])
X_Test['FreshTyre'] = le.fit_transform(X_Test['FreshTyre'])
X_Test['Driver'] = le.fit_transform(X_Test['Driver'])
X_Test['Team'] = le.fit_transform(X_Test['Team'])
X_Test = X_Test.dropna().reset_index(drop=True)
X_Test

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == "__main__":

    DriverNumber  LapNumber  Compound  FreshTyre  Stint  Team  Driver
0              1         25         1          1      1     8      17
1              1         26         1          1      1     8      17
2              1         56         0          1      2     8      17
3              1         57         0          1      2     8      17
4             16         23         1          1      1     4       6
..           ...        ...       ...        ...    ...   ...     ...
85             4         18         1          1      1     6       9
86             4         38         0          1      2     6       9
87             4         39         0          1      2     6       9
88            24          5         1          1      1     0      19
89            24          6         1          1      1     0      19

[90 rows x 7 columns]

**Predicting Model**

In [9]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators = 100, random_state = 0)
model.fit(X_Train, Y_Train)
Y_test = model.predict(X_Test)
soft = 0
softcount = 0
medium = 0
mediumcount = 0
hard = 0
hardcount = 0
print("Driver Tyre Actual Predicted")
for i in range(0, len(Test['Driver'])):
    if(Test['Compound'][i] == 'SOFT'):
        soft = soft + Y_test[i]
        softcount = softcount + 1
    elif(Test['Compound'][i] == 'MEDIUM'):
        medium = medium + Y_test[i]
        mediumcount = mediumcount + 1
    elif(Test['Compound'][i] == 'HARD'):
        hard = hard + Y_test[i]
        hardcount = hardcount + 1
    print(Test['Driver'][i], Test['Compound'][i], Test['TyreLife'][i], Y_test[i])

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

Driver Tyre Actual Predicted
VER MEDIUM 25.0 21.34
VER MEDIUM 26.0 20.82
VER HARD 30.0 36.38
VER HARD 31.0 36.11
LEC MEDIUM 23.0 21.85
LEC MEDIUM 24.0 21.82
LEC HARD 32.0 36.69
LEC HARD 33.0 35.71
SAI MEDIUM 26.0 21.01
SAI MEDIUM 27.0 20.5
SAI HARD 29.0 38.67
SAI HARD 30.0 38.34
PER MEDIUM 26.0 20.87
PER MEDIUM 27.0 19.97
PER HARD 13.0 20.29
PER HARD 14.0 20.3
PER MEDIUM 15.0 17.31
PER MEDIUM 16.0 21.64
RUS HARD 39.0 35.62
RUS HARD 40.0 35.78
RUS MEDIUM 16.0 28.96
RUS MEDIUM 17.0 29.64
HAM MEDIUM 21.0 20.67
HAM MEDIUM 22.0 21.4
HAM HARD 34.0 36.85
HAM HARD 35.0 35.48
BOT MEDIUM 25.0 20.85
BOT MEDIUM 26.0 20.79
BOT HARD 30.0 36.56
BOT HARD 31.0 35.63
OCO HARD 40.0 37.17
OCO HARD 41.0 37.2
OCO SOFT 15.0 24.74
OCO SOFT 16.0 25.45
ALB MEDIUM 15.0 14.96
ALB MEDIUM 16.0 15.86
ALB HARD 40.0 37.78
ALB HARD 41.0 37.58
STR HARD 41.0 33.27
STR HARD 42.0 33.26
STR MEDIUM 18.0 25.92
STR MEDIUM 19.0 27.84
ALO MEDIUM 14.0 14.0
ALO MEDIUM 15.0 15.0
ALO HARD 42.0 36.64
ALO HARD 43.0 36.26
TSU MEDIUM 10.0 12.8
TSU MEDIUM 11.0 12.9
TSU HARD 29.0 22.79
TSU HARD 30.0 22.63
TSU SOFT 18.0 16.7
TSU SOFT 19.0 19.01
RIC MEDIUM 29.0 20.1
RIC MEDIUM 30.0 20.32
RIC HARD 10.0 19.73
RIC HARD 11.0 19.61
RIC SOFT 15.0 15.18
RIC SOFT 16.0 17.55
LAT HARD 33.0 23.38
LAT HARD 34.0 23.82
LAT MEDIUM 22.0 24.72
LAT MEDIUM 23.0 27.42
MSC MEDIUM 13.0 13.19
MSC MEDIUM 14.0 14.08
MSC HARD 39.0 34.34
MSC HARD 40.0 38.25
MSC MEDIUM 2.0 17.16
MSC MEDIUM 3.0 21.04
MAG MEDIUM 11.0 12.04
MAG MEDIUM 12.0 12.25
MAG HARD 29.0 22.54
MAG HARD 30.0 21.47
MAG MEDIUM 14.0 16.14
MAG MEDIUM 15.0 20.37
VET HARD 42.0 27.64
VET HARD 43.0 27.78
VET MEDIUM 14.0 29.58
VET MEDIUM 15.0 29.88
GAS MEDIUM 15.0 15.0
GAS MEDIUM 16.0 16.0
GAS HARD 23.0 21.34
GAS HARD 24.0 20.44
GAS SOFT 7.0 10.85
GAS SOFT 8.0 11.03
NOR MEDIUM 17.0 17.05
NOR MEDIUM 18.0 18.03
NOR HARD 20.0 18.85
NOR HARD 21.0 18.49
ZHO MEDIUM 5.0 3.88
ZHO MEDIUM 6.0 4.33

**Average of Each Tyre**

In [10]:
softlife = soft/softcount
mediumlife = medium/mediumcount
hardlife = hard/hardcount
print("Soft:", softlife)
print("Medium:", mediumlife)
print("Hard:", hardlife)
print("Race 5 has 57 laps")

Soft: 17.563750000000002
Medium: 19.120454545454546
Hard: 30.280789473684212
Race 5 has 57 laps

In [11]:
from xgboost import XGBRegressor

model = XGBRegressor()
model.fit(X_Train, Y_Train)
Y_test = model.predict(X_Test)
print("Driver Tyre Actual Predicted")
for i in range(0, len(Test['Driver'])):
    print(Test['Driver'][i], Test['Compound'][i], Test['TyreLife'][i], Y_test[i])

Driver Tyre Actual Predicted
VER MEDIUM 25.0 23.295958
VER MEDIUM 26.0 22.94135
VER HARD 30.0 35.941525
VER HARD 31.0 36.538925
LEC MEDIUM 23.0 22.740807
LEC MEDIUM 24.0 22.97222
LEC HARD 32.0 35.77495
LEC HARD 33.0 35.615593
SAI MEDIUM 26.0 22.761425
SAI MEDIUM 27.0 22.93109
SAI HARD 29.0 34.43938
SAI HARD 30.0 35.335068
PER MEDIUM 26.0 23.29788
PER MEDIUM 27.0 23.502836
PER HARD 13.0 17.649836
PER HARD 14.0 18.353638
PER MEDIUM 15.0 22.239964
PER MEDIUM 16.0 22.87882
RUS HARD 39.0 39.435307
RUS HARD 40.0 40.551796
RUS MEDIUM 16.0 28.570293
RUS MEDIUM 17.0 31.12711
HAM MEDIUM 21.0 20.869942
HAM MEDIUM 22.0 21.894148
HAM HARD 34.0 33.974693
HAM HARD 35.0 35.044205
BOT MEDIUM 25.0 23.086468
BOT MEDIUM 26.0 22.843319
BOT HARD 30.0 33.808365
BOT HARD 31.0 34.99699
OCO HARD 40.0 39.80503
OCO HARD 41.0 39.898247
OCO SOFT 15.0 30.427023
OCO SOFT 16.0 33.704285
ALB MEDIUM 15.0 15.145457
ALB MEDIUM 16.0 15.992579
ALB HARD 40.0 37.438194
ALB HARD 41.0 38.195717
STR HARD 41.0 38.948795
STR HARD 42.0 39.295017
STR MEDIUM 18.0 31.746223
STR MEDIUM 19.0 33.389706
ALO MEDIUM 14.0 13.808995
ALO MEDIUM 15.0 14.898812
ALO HARD 42.0 32.76153
ALO HARD 43.0 32.812874
TSU MEDIUM 10.0 11.204089
TSU MEDIUM 11.0 11.204089
TSU HARD 29.0 18.520535
TSU HARD 30.0 18.79682
TSU SOFT 18.0 24.60905
TSU SOFT 19.0 27.186487
RIC MEDIUM 29.0 22.851587
RIC MEDIUM 30.0 23.589024
RIC HARD 10.0 16.620813
RIC HARD 11.0 17.430084
RIC SOFT 15.0 21.169638
RIC SOFT 16.0 21.933342
LAT HARD 33.0 25.123005
LAT HARD 34.0 29.8192
LAT MEDIUM 22.0 14.479349
LAT MEDIUM 23.0 23.394863
MSC MEDIUM 13.0 12.785771
MSC MEDIUM 14.0 13.750076
MSC HARD 39.0 33.991158
MSC HARD 40.0 33.797184
MSC MEDIUM 2.0 12.840514
MSC MEDIUM 3.0 14.514071
MAG MEDIUM 11.0 11.193254
MAG MEDIUM 12.0 11.839619
MAG HARD 29.0 20.113192
MAG HARD 30.0 18.186504
MAG MEDIUM 14.0 14.291471
MAG MEDIUM 15.0 14.540394
VET HARD 42.0 35.38362
VET HARD 43.0 35.796772
VET MEDIUM 14.0 32.38634
VET MEDIUM 15.0 31.992085
GAS MEDIUM 15.0 14.972399
GAS MEDIUM 16.0 16.000238
GAS HARD 23.0 18.76439
GAS HARD 24.0 17.832571
GAS SOFT 7.0 11.099766
GAS SOFT 8.0 12.202594
NOR MEDIUM 17.0 17.088243
NOR MEDIUM 18.0 18.065796
NOR HARD 20.0 20.131323
NOR HARD 21.0 18.41744
ZHO MEDIUM 5.0 4.0947337
ZHO MEDIUM 6.0 5.0497084